CREATE TABLE IF NOT EXISTS meeting (
  id INT AUTO_INCREMENT PRIMARY KEY,
  full_name VARCHAR(255),
  email      VARCHAR(255) UNIQUE NOT NULL,
  phone      VARCHAR(20),
  business   VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);